/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/ngx-presigned-uploader.module';
import * as import2 from '@angular/common';
class NgxPresignedUploaderModuleInjector extends import0.ɵNgModuleInjector<import1.NgxPresignedUploaderModule> {
  _CommonModule_0:import2.CommonModule;
  _NgxPresignedUploaderModule_1:import1.NgxPresignedUploaderModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.NgxPresignedUploaderModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._NgxPresignedUploaderModule_1 = new import1.NgxPresignedUploaderModule();
    return this._NgxPresignedUploaderModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.NgxPresignedUploaderModule)) { return this._NgxPresignedUploaderModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgxPresignedUploaderModuleNgFactory:import0.NgModuleFactory<import1.NgxPresignedUploaderModule> = new import0.NgModuleFactory<any>(NgxPresignedUploaderModuleInjector,import1.NgxPresignedUploaderModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21pa21hay93b3Jrc3BhY2VzL3Nwb3Rpbmkvbmd4LXByZXNpZ25lZC11cGxvYWRlci9zcmMvbmd4LXByZXNpZ25lZC11cGxvYWRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
