/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/presigned-uploader.component';
import * as import2 from '@angular/http';
const styles_PresignedUploaderComponent:any[] = ([] as any[]);
export const RenderType_PresignedUploaderComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PresignedUploaderComponent,
  data: {}
}
);
export function View_PresignedUploaderComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'input',[
      [
        'accept',
        '.jpeg,.jpg,.png'
      ]
      ,
      [
        'placeholder',
        'Upload file'
      ]
      ,
      [
        'type',
        'file'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'change'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.PresignedUploaderComponent = v.component;
      if (('change' === en)) {
        const pd_0:any = ((<any>co.fileChange($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_PresignedUploaderComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'presigned-uploader',([] as any[]),(null as any),(null as any),(null as any),View_PresignedUploaderComponent_0,RenderType_PresignedUploaderComponent)),
    import0.ɵdid(114688,(null as any),0,import1.PresignedUploaderComponent,[import2.Http],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PresignedUploaderComponentNgFactory:import0.ComponentFactory<import1.PresignedUploaderComponent> = import0.ɵccf('presigned-uploader',import1.PresignedUploaderComponent,View_PresignedUploaderComponent_Host_0,{
  presignedUrl: 'presignedUrl',
  serverEndpoint: 'serverEndpoint',
  headers: 'headers'
}
,{uploadState: 'uploadState'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9taWttYWsvd29ya3NwYWNlcy9zcG90aW5pL25neC1wcmVzaWduZWQtdXBsb2FkZXIvc3JjL3ByZXNpZ25lZC11cGxvYWRlci5jb21wb25lbnQudHMuUHJlc2lnbmVkVXBsb2FkZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50LnRzLlByZXNpZ25lZFVwbG9hZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0ICA8aW5wdXQgdHlwZT1cImZpbGVcIiAoY2hhbmdlKT1cImZpbGVDaGFuZ2UoJGV2ZW50KVwiIHBsYWNlaG9sZGVyPVwiVXBsb2FkIGZpbGVcIiBhY2NlcHQ9XCIuanBlZywuanBnLC5wbmdcIj5cblx0IiwiPHByZXNpZ25lZC11cGxvYWRlcj48L3ByZXNpZ25lZC11cGxvYWRlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQW1CO1FBQUE7UUFBQTtNQUFBO01BQW5CO0lBQUE7SUFBb0c7Ozs7OztJQ0R4RztnQkFBQTs7O0lBQUE7Ozs7Ozs7OyJ9
