/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/presigned-uploader.component';
import * as import2 from '@angular/http';
const styles_PresignedUploaderComponent:any[] = ([] as any[]);
export const RenderType_PresignedUploaderComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PresignedUploaderComponent,
  data: {}
}
);
export function View_PresignedUploaderComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'input',[
      [
        'placeholder',
        'Upload file'
      ]
      ,
      [
        'type',
        'file'
      ]

    ]
      ,[[
        8,
        'accept',
        0
      ]
      ],[[
        (null as any),
        'change'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.PresignedUploaderComponent = v.component;
      if (('change' === en)) {
        const pd_0:any = ((<any>co.fileChange($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.PresignedUploaderComponent = v.component;
    const currVal_0:any = import0.ɵinlineInterpolate(1,'',co.fileTypes,'');
    ck(v,1,0,currVal_0);
  });
}
function View_PresignedUploaderComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'presigned-uploader',([] as any[]),(null as any),(null as any),(null as any),View_PresignedUploaderComponent_0,RenderType_PresignedUploaderComponent)),
    import0.ɵdid(114688,(null as any),0,import1.PresignedUploaderComponent,[import2.Http],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PresignedUploaderComponentNgFactory:import0.ComponentFactory<import1.PresignedUploaderComponent> = import0.ɵccf('presigned-uploader',import1.PresignedUploaderComponent,View_PresignedUploaderComponent_Host_0,{
  presignedUrl: 'presignedUrl',
  serverEndpoint: 'serverEndpoint',
  headers: 'headers',
  s3Prefix: 's3Prefix',
  fileTypes: 'fileTypes',
  action: 'action'
}
,{
  uploadState: 'uploadState',
  completed: 'completed'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9taWttYWsvd29ya3NwYWNlcy9zcG90aW5pL25neC1wcmVzaWduZWQtdXBsb2FkZXIvc3JjL3ByZXNpZ25lZC11cGxvYWRlci5jb21wb25lbnQudHMuUHJlc2lnbmVkVXBsb2FkZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWlrbWFrL3dvcmtzcGFjZXMvc3BvdGluaS9uZ3gtcHJlc2lnbmVkLXVwbG9hZGVyL3NyYy9wcmVzaWduZWQtdXBsb2FkZXIuY29tcG9uZW50LnRzLlByZXNpZ25lZFVwbG9hZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0ICA8aW5wdXQgdHlwZT1cImZpbGVcIiAoY2hhbmdlKT1cImZpbGVDaGFuZ2UoJGV2ZW50KVwiIHBsYWNlaG9sZGVyPVwiVXBsb2FkIGZpbGVcIiBhY2NlcHQ9XCJ7e2ZpbGVUeXBlc319XCI+XG5cdCIsIjxwcmVzaWduZWQtdXBsb2FkZXI+PC9wcmVzaWduZWQtdXBsb2FkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBbUI7UUFBQTtRQUFBO01BQUE7TUFBbkI7SUFBQTtJQUFrRzs7OztJQUF2QjtJQUEzRSxTQUEyRSxTQUEzRTs7Ozs7SUNESjtnQkFBQTs7O0lBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
